### ISSUE TITLE
Reid Bug

### ISSUE THREAD

**Issue by rjmajma** [18F/openFEC#477] opened 2015-03-12 15:18 UTC
For some reason, the typeahead picks up Harry Reid but this does not show up in the search results. The problem seems to be on the API side. 

CC @arowla or @LindsayYoung

**Comment by micahsaul** [comment] 2015-03-12 16:38
D Adam Smith is not showing up in the search results for "smith" either. cand_id: H6WA09025

**Comment by arowla** [comment] 2015-03-16 17:44
So this looks to be a problem with the default year filter (currently limiting everything to 2011, 2012, 2013, 2014). Harry Reid's election_years are showing up as 2004, 2010, 2016, so there is no overlap.

**Comment by arowla** [comment] 2015-03-16 17:46
BTW... I haven't quite got it figured out, but D Adam Smith stems from a different problem, I think.

**Comment by arowla** [comment] 2015-03-16 18:03
@micahsaul Actually, I'm not able to reproduce the problem with D Adam Smith. I see him in the results here (where localhost is running the latest version of master):

http://localhost:3000/candidates?q=smith

**Comment by LindsayYoung** [comment] 2015-03-17 01:31
Regarding the Reid issue, I think this is going to be more clear when we have year filtering clearly implemented on the front end. I know that going 4 years was going to miss a class of Senators at any given time, but am intrigued to see that he is listed for 2016. Perhaps we should add the future year to our default year filtering.

**Comment by LindsayYoung** [comment] 2015-03-23 21:03
closed by pr #447

**Closed by LindsayYoung** 2015-03-23 21:03 UTC
Labels: bug
