### ISSUE TITLE
Search discrepancy

### ISSUE THREAD

**Issue by gmj2053** [18F/openFEC#1601] opened 2016-04-05 16:10 UTC
When I search for a name that the API feed pulled into our tool to process for webarchiving, I can't find it.  But if I do a pagination through for 2016 candidates, I see the name.  
examples
John Marshall Blust 
William David Bledsoe
![1](https://cloud.githubusercontent.com/assets/6361652/14289073/53062c2a-fb27-11e5-9ea6-f8af1d3c4f50.jpg)

![2](https://cloud.githubusercontent.com/assets/6361652/14289100/686a832c-fb27-11e5-9ceb-2155489a49df.jpg)

**Comment by LindsayYoung** [comment] 2016-04-05 17:33
Thanks for reporting this issue! I will take a look and see what is going on.

**Comment by LindsayYoung** [comment] 2016-04-05 22:27
This is a weird error that we are looking into. If you notice this with any other candidates, that would be helpful to know. We will keep working on this and update you when the issue is resolved.

**Comment by gmj2053** [comment] 2016-04-06 11:35
Working fine now, I checked the other 19 candidates we just ingested and they came up in search fine.

thanks, our tool ingests weekly on mondays so, will check new ingest then.

Thanks for all the good work!

**Comment by LindsayYoung** [comment] 2016-06-29 14:17
Closing this since it looks like everything was resolved a while ago. Thanks again for the bug reporting!

**Closed by LindsayYoung** 2016-06-29 14:17 UTC
Labels: bug
