### ISSUE TITLE
Create aggregates on FECP then transfer data to new website

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC#2724] opened 2017-10-31 19:38 UTC
This is derived from Issue https://github.com/18F/openFEC/issues/2686:  Golden Gate data loading time.

Need @jwchumley to take a look at the in progress.

**Comment by fecjjeng** [comment] 2017-11-01 01:37
This is derived from Issue#2686:  Golden Gate data loading time.
Currently the transfer rate from fecp to the cloud databases of three biggest tables (disclosure.f_item_receipt_or_exp, disclosure.nml_sched_a, disclosure.nml_sched_b) is very slow using Golden Gate.  We switched to using Java program to do the transfer, it is faster than Golden Gate, but still very slow.  Also when using multi-sessions transfer to increase the efficiency of transfer, we also encountered dead-lock issues.  The major cause for the slowness is the triggers on these tables that handled two tasks: 1. insert rows into sub-tables partitioned by election cycle.  2. calculate aggregates of transactions based on several criteria.  
In order to remove the triggers so the data for the big three tables can be transferred in an acceptable rate, we need to provide the same data these triggers provided.  
The sub-tables partitioned by election cycle are already transferred using Java programs as discussed in previous meetings.  This issue is to deal with the calculate aggregates of transactions based on several criteria, perform the calculation on the fecp side and transfer the results to the clouds.

**Comment by fecjjeng** [comment] 2017-11-01 01:42
We reviewed the plpgsql code that used to calculate the aggregates in the cloud databases, discussed the business logic with @PaulClark2 @jwchumley , @LindsayYoung @ccostino in email, Slack, and in person.  Following is the summary of the discussion:

1.	The logic in function “is_not_committee” itself is incorrect.  
2.	We will not include the call to the “is_not_committee” in the call to the is_individual.
(that is, we are going to the follow the version of is_individual function in pg database that is used to calculate the is_individual column)
3.	For the aggregate on zip code, we will use the max(state) as the pg database to avoid the unique key violation problem caused by filer file the incorrect the state with the ZIP code.  Even the State information may not be correct, since the aggregation is on the zip code, the State is just an auxiliary information, it is acceptable.
4.	For the aggregate on zip code, we  will use the 5 digit zip code.  
Substr(zip_code, 1, 5)
5.	For transaction_amt = 0 entries, Paul said RAD is in the process of working with the committees not to do so in the future.  
6.	For earmark check:
a.	The is_earmark function is correct (that is, memo_cd =’X’ AND the memo_text containing the word earmark, etc).  However, for the sched_a is_individual check, since most of the earmark entries had been coded correctly by transaction_tp , it is acceptable to just check if memto_cd  is NULL  in the is_inferred_individual.
b.	For the sched_b, the query does not have the coding check.  Even in cases that has both earmark/nonearmark rows, it would be ideally only take the earmarked rows, but if we only take the earmarked rows, we will miss most normal rows that without a earmarked counterpart.  Therefore Paul’s conclusion is that for now let's stick with the original logic and we'll figure out the case (such as the credit card payments vs detailed earmarked items) later. 
7.	For the check for unitem, currently the pg code only exclude the un-itemized rows when aggregate sa_agg_state, this filter should be applied to all SA aggregates.  
8.	For the Sched_B Agg on recipient_id and recipient_nm, we added a filter TRANSACTION_TP IN ('15E','15Z','16H','16K','16R','17R','17Z','18G','18J','18K','20R',
'22H','22K','22Z','24G','24I','24K','24R','24T','24Z','40Z','41Z','42Z') to get rows that should be relavent.  Jeff had confirmed TRANSACTION_TP that are not in this list should be excluded.

**Comment by fecjjeng** [comment] 2017-11-01 01:48
Currently, coding of the PL/SQL package and Java programs are done.  Initial load into the cloud databases of the 8 aggregate tables just finished.  The initial load are into separated set of tables in a different schema (disclosure) so not to impact any current APIs accessing the aggregate tables in public schema.  We will start testing the daily updates process tomorrow.

**Comment by fecjjeng** [comment] 2017-11-01 01:51
These sets of tables has exactly the same table structure as the current tables in the public schema except the schema name.

**Comment by PaulClark2** [comment] 2017-11-01 11:29
Tagging @vrajmohan into this discussion

**Comment by fecjjeng** [comment] 2017-11-29 15:48
@hcaofec The business logic for SB_AGG_Recipient had been updated and tables in all cloud environment reloaded with updated logic.

**Comment by hcaofec** [comment] 2017-11-30 19:53
Reviewed SB_AGG_Recipient table and it looks good.
@jwchumley @PaulClark2 @fecjjeng

**Comment by hcaofec** [comment] 2017-12-04 15:56
All 8 aggregate tables are created and the data has been reviewed. A separate issue is created to track deployment.

**Closed by hcaofec** 2017-12-04 15:56 UTC
Labels: High priority
