### ISSUE TITLE
Profile summary issue

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC#2431] opened 2017-05-25 21:47 UTC
I think this is similar to the Lessig issue #2419 where he changed committee time and form type. Sometimes committees file accidentally on the wrong form. When that happens the summary numbers need to add into the total for the committee, In oldfec that happened in v_sum. In newFEC I think the form_type is part of the criteria for including a report in the summary i.e. if the filer is a house committee then we are only including form 3. That will need to change.

**Comment by noahmanger** [comment] 2017-08-08 17:25
Duplicate of https://github.com/18F/openFEC/issues/2419

**Closed by noahmanger** 2017-08-08 17:25 UTC
Labels: Needs grooming
