### ISSUE TITLE
So users can find the election search, redesign search to be more prominent

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC#1184] opened 2015-09-08 19:33 UTC
Some (~ half) of the users we tested were not able to successfully navigate from the home page to the election search. 

There are probably a couple things going on here: the usability task prompt “find people running for office near you” requires the user to think of “near” as indicating location, and then to infer that zip code is a way to find candidates based on their location (instead, these users navigated to “browse candidates” and searched by state there). Given that you can not only search by zip code but also by state and district, it’s perhaps worth revisiting the menu item title, “Search by Zip code” to be more inclusive of the ways you can search and to be an easier mental translation by the users. 

revising the navigation item "search by zip code". Not exactly sure how, possibly "election look-up" or similar? @emileighoutlaw; what are your thoughts?

This is also referenced in issue #1183 

Usability Task:
Use the site to find people running for office near you.

**Comment by leahbannon** [comment] 2015-09-09 00:23
Related: https://github.com/18F/openFEC-web-app/issues/545

**Comment by emileighoutlaw** [comment] 2015-09-09 01:34
I think we're decided on "Search elections by location" for now!

**Comment by leahbannon** [comment] 2015-09-09 16:27
Addressed in https://github.com/18F/openFEC-web-app/issues/545

**Comment by jenniferthibault** [comment] 2015-10-02 16:55
Re-opening this issue in favor of closing out https://github.com/18F/openFEC-web-app/issues/545 since this issue has the user research data in it, and most recent discussion.

**Comment by jenniferthibault** [comment] 2015-10-02 17:06
@noahmanger and I were just discussing a visual proposal that might help this issue. I doubt that it will solve all the problems, but I believe strongly that part of the issue is that the nav, as is, is quite low contrast in it's info hierarchy. Meaning—each sub-item looks identical to the main nav item typographically, in terms of visual spacing.

Current:
<img width="310" alt="screen shot 2015-10-02 at 12 59 35 pm" src="https://cloud.githubusercontent.com/assets/11636908/10252440/7a37dbc2-6905-11e5-88b3-33b44f9110dd.png">

Proposed:
 - change the sub-nav font to Karla, using Karla Bold to show secondary items, and Karla Regular, combined with an indent, to show tertiary items. 
 - A border line will help maintain discrete sections. 
 - I also believe that putting the "Find candidates by location" item at the end of the list (and more towards the border of the nav) will help. This might seem counter-intuitive, but it seemed to be hiding when it was first on the list. I think all these things combined are visually helpful:
 - while we're at it, let's make the activated nav the primary blue, which needed to be done anyways so that the desktop nap and mobile nav had the same color scheme

![screen shot 2015-10-02 at 1 05 48 pm](https://cloud.githubusercontent.com/assets/11636908/10252571/53e6efac-6906-11e5-8fea-5411edde7edc.png)

**Comment by emileighoutlaw** [comment] 2015-10-05 14:36
Ohhh interesting! I hope this works!!

**Comment by jenniferthibault** [comment] 2015-10-13 19:21
@onezerojeremy / @noahmanger 

I got some good feedback from @colinpmacarthur & @bradnunnally on this, which resulted in a re-design of the data landing page to prioritize this feature, since I heard that you believed it's use cases necessitated a bump up in priority.  Here's what this could look like:

![data home 4](https://cloud.githubusercontent.com/assets/11636908/10465600/9d67c9de-71bd-11e5-8aaf-edcf333de31a.png)

A couple thoughts outstanding that I could use more brains on:
 - there is some redundancy in the hero search bar and the candidate/elections search right under it. They bring you to different places, and allow you to do different things, but I only know that from being a frequent user of the site
 - I'm not sure exactly what features we want to call out or visualize in any way, but with help figuring out what those are, I can come up with alternative visuals to just the screen shots in browser windows. I took a basic guess here.

**Comment by LindsayYoung** [comment] 2015-10-13 19:33
That looks good. 

Does this mean we are dropping the high-level stats for the presidential election?

**Comment by jenniferthibault** [comment] 2015-10-13 19:40
Ah! I forgot to put that back in :) Was thinking that I we can instead pair it with the most recent filings. Will be back in a few with a new mock up

**Comment by onezerojeremy** [comment] 2015-10-13 19:55
This direction feels very strong and in line with the research findings heretofore (that users are still struggling to understand the capabilities of the tool from the nav item's 3 words). I love how you're exposing the functionality on the site, and giving users a sense of what they'll get. 

Two thoughts: 
1. I think I might even push for it to be on the beta home page (so it's at the trailhead, so to speak), as opposed to in the "explore campaign finance data" section. The side benefit of moving this is that currently, the tool feels a bit more prominent than the candidate search to me. Could just be me, though.

2. I like the idea of visualizations which show something about the data simultaneously show how the tool works. We'll no doubt need to have a full measure of caution in choosing what to focus on, so as not to be seen as "editorializing". Even just screenshots to start feels like a good MVP. 

Nice work!

**Comment by jenniferthibault** [comment] 2015-10-14 14:34
A things I want to make sure I understand @onezerojeremy — From your first point, what should the hierarchy be between the candidate/committee search and the election search? Equal? Or one with more visual priority?

**Comment by onezerojeremy** [comment] 2015-10-14 14:57
I don't have any evidence on this, so I'd like @noahmanger to weigh in as he was doing this research around user goals for this feature long before I came on the project.

That said, my impression is that getting people to view a candidate is probably our first priority goal, with election being second.

**Comment by jenniferthibault** [comment] 2015-10-14 14:59
OK—that is the reverse of how I had understood it, which may influence the below mockups, but I didn't want to wait too long to get started on a few other ideas...

I explored a very different concept with @esgoodman 's brainstorming ideas from our critique, which mirrored some of the ideas Colin, Brad, and I were thinking of, but I hadn't tried yet. Here's an approach that collapses all three types of search into one tab-like hero module that the user can toggle between for searches. I think it's successful in not pulling users' attention in as many directions as the last mockup (and previous ones) did.

#### Default view on elections search
The one that may fit users' mental models best, but can be the most complex when not introduced properly

![data home 4 copy 2](https://cloud.githubusercontent.com/assets/11636908/10487476/1f76a694-7262-11e5-9d37-767c06ba8349.png)

#### Toggle to candidate search
Screenshots TBD
![data home 4 copy 3](https://cloud.githubusercontent.com/assets/11636908/10487475/1f754a56-7262-11e5-99c6-5ed781626dc8.png)

#### Toggle to committee search
Screenshots TBD
![data home 4 copy 4](https://cloud.githubusercontent.com/assets/11636908/10487474/1f734a4e-7262-11e5-855c-3ad57e15482b.png)

**Comment by jenniferthibault** [comment] 2015-10-14 15:00
Annnnnd a reconstructed home page that would work the feature in as it's own thing. I don't love it visually, so consider this more of a wireframe for placement and priority of elements, then I can figure out a better visual solution. Is this what you meant @onezerojeremy ? :

<img width="586" alt="screen shot 2015-10-14 at 10 52 33 am" src="https://cloud.githubusercontent.com/assets/11636908/10487602/b8dfdd00-7262-11e5-9b33-303cb518896f.png">

**Comment by noahmanger** [comment] 2015-11-12 23:41
Storymap card: https://18f.storiesonboard.com/m/fec/!card/NpijpDh1xZKvaTnUD8RvAQ

**Comment by LindsayYoung** [comment] 2016-06-14 15:36
This is from March, should it still be open?

**Comment by noahmanger** [comment] 2016-06-14 16:41
Considering we have a new landing page, we can close it.

**Closed by noahmanger** 2016-06-14 16:41 UTC
Labels: backlog, has-story
