### ISSUE TITLE
Bug: Error when specifying cycle for committee C00315622

### ISSUE THREAD

**Issue by Solomon** [18F/openFEC#1187] opened 2015-09-09 00:43 UTC
When hitting the api with this committee: C00315622

/committee/{committee_id}/totals gives a result for the 1996 cycle

However, when I add the 1996 cycle to the api request, it fails.

Doesn't work: `https://api.open.fec.gov/v1/committee/C00315622/totals?api_key={key}&cycle=1996&page=1&per_page=20`

Shows results for 1996: `https://api.open.fec.gov/v1/committee/C00315622/totals?api_key={key}&page=1&per_page=20`

**Comment by LindsayYoung** [comment] 2015-09-09 14:53
Thanks for reporting @Solomon 

I am seeing the same problem on reports.  It is returning a 404. The same issue exists on dev as well.

**Comment by LindsayYoung** [comment] 2015-09-09 15:00
Filtering by 1998 works, but not 1996.

**Comment by LindsayYoung** [comment] 2015-09-10 16:36
Ok, It seems like the committee doesn't have a committee designation entry for 1996.

**Comment by leahbannon** [comment] 2015-10-05 19:46
is this a question for @PaulClark2 ?

**Comment by PaulClark2** [comment] 2015-10-06 18:22
Is this still an issue?   I see a committee designation for C00315622, it's "P."   Am I looking in the wrong tables?   

select d.cmte_dsgn, d.* from dimcmtetpdsgn d where cmte_sk = 10033040;
select l.cmte_dsgn, l.* from DIMLINKAGES l where cmte_sk = 10033040;

select * from dimcmte where cmte_id= 'C00315622';
select  * from DIMCMTEPROPERTIES d where cmte_sk = 10033040;

**Comment by leahbannon** [comment] 2015-10-13 19:49
I'm closing this since it looks like it may have been resolved. Feel free to reopen if it's still an issue.

**Comment by LindsayYoung** [comment] 2015-10-13 20:01
These still aren't working. there should be results for the 1996 cycle according to fec.gov. I haven't had time to dig any deeper on this lately. Maybe it is caused by a different issue. I would like to figure this out.

I am getting a 404 on dev and produciton: 
https://api.open.fec.gov/v1/committee/C00315622/totals/?cycle=1996&page=1&per_page=20&api_key=DEMO_KEY

I am getting a 500 on production and no results on dev: 
https://api.open.fec.gov/v1/committee/C00315622/totals/?page=1&per_page=20&api_key=DEMO_KEY

**Comment by jmcarp** [comment] 2015-11-03 17:04
Update: as with many committee-related issues, this one appears to be fixed when we switch to a higher-quality table (`cmte_valid_fec_yr`) in #1325. I'm hoping to get that patch deployed to production in the next release.

**Comment by noahmanger** [comment] 2015-11-12 21:05
This is now working on the dev api and will be deployed to production. Closing this.

**Closed by noahmanger** 2015-11-12 21:05 UTC
Labels: backlog, bug
