### ISSUE TITLE
/schedules/shedule* endpoints not returning event date

### ISSUE THREAD

**Issue by himynamesdave** [18F/openFEC#1132] opened 2015-08-16 13:02 UTC
"receipt_date" and "contributor_receipt_date" fields are not returned in all results for the endpoints /schedules/schedule* (even with "sort_hide_null"="false").

These are important fields because other dates returned like "update_date", "load_date" and "expiry_date" do not reflect data of actual event (donation, etc).

**Comment by LindsayYoung** [comment] 2015-08-16 14:00
Thank you for reporting this @himynamesdave  

@jmcarp I think the easiest way to fix this is to release some of the new stuff. I will take a look at it today and we can flag the FEC to take a look on Monday. I am also going to make the name changes we were talking about since those variables weren't publicly exposed anyway. Sound good?

**Comment by himynamesdave** [comment] 2015-08-27 14:08
There are a number of other discrepancies I've noticed between the docs and what is returned in some responses.

We currently have a set of samples from the FEC API indexed into Splunk which I would be happy to work through with you guys.

![download](https://cloud.githubusercontent.com/assets/1296409/9522506/28f6e798-4ccd-11e5-9546-add9df6b8078.png)

**Comment by LindsayYoung** [comment] 2015-11-13 18:05
We fixed this quite a while ago but I forgot to close the issue. 

I just confirmed that all the transaction dates are available.

In schedule_b I now see `disbursement_date`
https://api.open.fec.gov/v1/schedules/schedule_b/?api_key=DEMO_KEY

In schedule_a I am seeing `contribution_receipt_date `
https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY

In schedule_e I am seeing `expenditure_date`
https://api.open.fec.gov/v1/schedules/schedule_e/?api_key=DEMO_KEY


Thanks for writing in and we would love to hear additional feedback.!

**Closed by LindsayYoung** 2015-11-13 18:05 UTC
Labels: candidates, community-question, FEC-data, icebox
