### ISSUE TITLE
Investigate delay in MUR/AO refresh documents appearing

### ISSUE THREAD

**Issue by lbeaufort** [18F/openFEC#2816] opened 2017-12-14 17:23 UTC
We're having an issue where after AO's and MURs are refreshed, newly published documents are appearing intermittently for approximately 40 minutes.

- [x] Document ID's for legal docs, which come from postgres but seem to be changing over time: `select document_id, category, filename from aouser.document where ao_id = 4530;`
- [x] Figure out why the document ID's are changing
- [x] Research logs to see if there's anything helpful there (See PR https://github.com/18F/openFEC/pull/2821)
- [ ] Try to replicate the issue

Example of ID's changing: 

12/14/2017 | Comment on Agenda Document No. 17-59-B by Campaign Legal Center
*was* https://www.fec.gov/files/legal/aos/83657.pdf (ID 83657) is now https://www.fec.gov/files/legal/aos/83664.pdf (ID 83664)
## Before
![image](https://user-images.githubusercontent.com/31420082/34005582-5d5d3e6e-e0c9-11e7-9c13-746163251cee.png)
## After
![image](https://user-images.githubusercontent.com/31420082/34005587-64916dfe-e0c9-11e7-8758-f350e57ca50d.png)

**Comment by vrajmohan** [comment] 2017-12-14 17:37
Nice work, I think you've identified the root cause. I think Salient ids change. Looks like when we refresh a document, we should delete the old documents from S3. Otherwise, the documents with the old ids will still linger with _nothing linking to them_

**Comment by LindsayYoung** [comment] 2017-12-14 18:22
@lbeaufort can FEC reach out to salient to see if they could implement stable IDs? We would really want permalinks for these.

**Comment by lbeaufort** [comment] 2017-12-14 18:50
As of 12/14, 1:30pm ET		
|document_id   |  category | filename  | 
|---------|------------------------------------------|---------------|
83679	|Comments and Ex parte Communications	|201712C_3.pdf
83680	|Comments and Ex parte Communications	|201712C_4.pdf
83681	|Draft Documents	|201712_2.pdf
83674	|AO Request, Supplemental Material, and Extensions of Time	|201712R_1.pdf
83675	|Draft Documents	|201712.pdf
83676	|Draft Documents	|201712_1.pdf
83677	|Comments and Ex parte Communications	|201712C_1.pdf
83678	|Comments and Ex parte Communications	|201712C_2.pdf

**Comment by lbeaufort** [comment] 2017-12-14 23:13
@LindsayYoung  - @jwchumley said he would reach out to Salient about keeping the document ID's the same.

**Comment by lbeaufort** [comment] 2017-12-15 17:44
@vrajmohan - Lindsay and I are going to put in a PR to target the 12/20 release to raise the logger level to INFO and add filename to the logger for the `get_documents()` function.

**Comment by jwchumley** [comment] 2017-12-15 17:59
Salient is looking at the code to confirm but I think this is a byproduct of the way they handle changes. If something Changes, Jason unpublished it and makes the change and republishes. I think it creates new rows for all the documents in that AO and new doc_ids even thought the documents may be exactly the same.

**Comment by AmyKort** [comment] 2017-12-21 14:04
Do we want to close this issue?

**Comment by lbeaufort** [comment] 2017-12-21 15:01
@AmyKort not quite yet - the hotfix needs to be merged. I'm reviewing now

**Comment by vrajmohan** [comment] 2018-01-02 17:11
IMO, this issue can be closed.

**Closed** 2018-01-02 17:49 UTC
Labels: High priority
